name: gleeky_flutter
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.6+10

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.5
  responsive_framework: ^0.1.9
  shared_preferences: ^2.0.16
  image_picker: ^0.8.6
  flutter_spinkit: ^5.1.0
  cached_network_image: ^3.2.0
  flutter_overlay_loader: ^2.0.0
  http: ^0.13.5
  dio: ^4.0.6
  flutter_rating_bar: ^4.0.1
  country_picker: ^2.0.19
  google_maps_flutter: ^2.2.3
  flutter_typeahead: ^4.1.1
  uuid: ^3.0.7
  geocoding: ^2.0.5
  geolocator: ^8.2.0
  syncfusion_flutter_datepicker: ^20.4.44
  fl_chart: ^0.60.0
  shimmer: ^2.0.0
  map_launcher: ^2.4.0
  intl: ^0.18.0
  pdf: ^3.8.4
  path_provider: ^2.0.12
  open_file: ^3.1.0
  url_launcher: ^6.1.9
  pull_to_refresh: ^2.0.0
  google_sign_in: ^6.0.1
  flutter_facebook_auth: ^5.0.8
  syncfusion_flutter_calendar: ^20.4.53
  flutter_bounce: ^1.1.0
  firebase_core: ^2.8.0
  firebase_messaging: ^14.3.0
  platform_device_id: ^1.0.1
  flutter_local_notifications: ^11.0.0
  share_plus: ^7.0.2
  flutter_staggered_grid_view: ^0.6.2
  easy_image_viewer: ^1.2.1
  auto_size_text: ^3.0.0
  simple_progress_indicators: ^0.2.0
  carousel_slider: ^4.2.1
  shimmer_animation: ^2.1.0+1
  open_app_file: ^4.0.2
  dropdown_search: ^5.0.6




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: HankenGrotesk
      fonts:
        - asset: assets/fonts/HankenGrotesk-Bold.ttf
          weight: 700
        - asset: assets/fonts/HankenGrotesk-Regular.ttf
          weight: 500
        - asset: assets/fonts/HankenGrotesk-Light.ttf
          weight: 400
        - asset: assets/fonts/HankenGrotesk-Thin.ttf
          weight: 300
        - asset: assets/fonts/HankenGrotesk-Italic.ttf
          weight: 500
          style: italic
